import { I18n } from '@mantou/gem/helper/i18n';

export const Resources = {
  en: {
    editOnGithub: 'Edit this page on GitHub',
    createOnGithub: 'Create on GitHub',
    footer: 'Generated by $1<gem-book>',
    lastUpdated: 'Last Updated',
  },
  zh: {
    editOnGithub: '在 Github 编辑此页',
    createOnGithub: '在 Github 上创建此页面',
    footer: '通过 $1<gem-book> 生成',
    lastUpdated: '上次更新',
  },
};

export const selfI18n = new I18n<typeof Resources.en>({
  fallbackLanguage: 'en',
  resources: Resources,
  // 默认是自动识别，如果不是多语言版本使用 `--template` 模版指定语言
  currentLanguage: document.documentElement.lang,
});
