export {};

declare global {
  const effect: typeof import('@mantou/gem')['effect'];
  const mounted: typeof import('@mantou/gem')['mounted'];
  const slot: typeof import('@mantou/gem')['slot'];
  const numattribute: typeof import('@mantou/gem')['numattribute'];
  const adoptedStyle: typeof import('@mantou/gem')['adoptedStyle'];
  const unmounted: typeof import('@mantou/gem')['unmounted'];
  const state: typeof import('@mantou/gem')['state'];
  const shadow: typeof import('@mantou/gem')['shadow'];
  const createState: typeof import('@mantou/gem')['createState'];
  const styleMap: typeof import('@mantou/gem')['styleMap'];
  const partMap: typeof import('@mantou/gem')['partMap'];
  const property: typeof import('@mantou/gem')['property'];
  const raw: typeof import('@mantou/gem')['raw'];
  const part: typeof import('@mantou/gem')['part'];
  const willMount: typeof import('@mantou/gem')['willMount'];
  const classMap: typeof import('@mantou/gem')['classMap'];
  const async: typeof import('@mantou/gem')['async'];
  const customElement: typeof import('@mantou/gem')['customElement'];
  const aria: typeof import('@mantou/gem')['aria'];
  const GemElement: typeof import('@mantou/gem')['GemElement'];
  const light: typeof import('@mantou/gem')['light'];
  const exportPartsMap: typeof import('@mantou/gem')['exportPartsMap'];
  const template: typeof import('@mantou/gem')['template'];
  const globalemitter: typeof import('@mantou/gem')['globalemitter'];
  const createStore: typeof import('@mantou/gem')['createStore'];
  const boolattribute: typeof import('@mantou/gem')['boolattribute'];
  const connectStore: typeof import('@mantou/gem')['connectStore'];
  const TemplateResult: typeof import('@mantou/gem')['TemplateResult'];
  const html: typeof import('@mantou/gem')['html'];
  const memo: typeof import('@mantou/gem')['memo'];
  const attribute: typeof import('@mantou/gem')['attribute'];
  const createRef: typeof import('@mantou/gem')['createRef'];
  const emitter: typeof import('@mantou/gem')['emitter'];
  const css: typeof import('@mantou/gem')['css'];
  const svg: typeof import('@mantou/gem')['svg'];
  const fallback: typeof import('@mantou/gem')['fallback'];
  const styled: typeof import('@mantou/gem')['styled'];
  const mathml: typeof import('@mantou/gem')['mathml'];
}
