name: Publish DuoyunUI

on:
  push:
    tags:
      - duoyun-ui@*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  duoyun-ui-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: yarn

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/duoyun-ui/package.json
          token: ${{ secrets.NPM_TOKEN }}
