name: Publish DuoyunUI

on:
  push:
    tags:
      - "duoyun-ui@**"

jobs:
  duoyun-ui-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn
      - run: cd packages/duoyun-ui
      - run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
