name: Publish Gem Devtools

on:
  workflow_dispatch:

jobs:
  gem-devtools-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # docs https://pnpm.io/continuous-integration#github-actions

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install

      - name: Build
        run: |
          export VERSION=$(node -e "console.log(require('./package.json').version)")

          export ZIP_NAME=gem_devtools-${VERSION}.zip
          export ZIP_PATH=packages/gem-devtools/build/${ZIP_NAME}
          echo ${ZIP_PATH}

          pnpm update:version

          pnpm build:zip

          echo "ZIP_PATH=${ZIP_PATH}" >> $GITHUB_ENV
        working-directory: packages/gem-devtools

      - uses: wdzeng/chrome-extension@v1
        with:
          extension-id: lgfpciakeemopebkmjajengljoakjfle
          zip-path: ${{ env.ZIP_PATH }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: "{2af13fd2-a726-41de-b3a1-4bf2cb91c105}"
          xpi-path: ${{ env.ZIP_PATH }}
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}
