name: Publish Gem Analyzer

on:
  push:
    tags:
      - gem-analyzer@*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gem-analyzer-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: pnpm install

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/gem-analyzer/package.json
          token: ${{ secrets.NPM_TOKEN }}
