name: Publish Gem

on:
  push:
    tags:
      - "@mantou/gem@*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gem-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: node -e "fs.writeFileSync('./packages/gem/src/lib/version.ts', 'export const version = \'' + require('./packages/gem/package.json').version + '\';\n')"
      - run: yarn

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/gem/package.json
          token: ${{ secrets.NPM_TOKEN }}
