id = "gem"
name = "Gem"
description = "Gem plugin for VS Code"
version = "0.0.1"
schema_version = 1
authors = ["mantou132 <709922234@qq.com>"]
repository = "https://github.com/mantou132/gem"
snippets = "./snippets/typescript.json"
