id = "gem"
name = "Gem"
description = "Gem plugin for Zed"
version = "0.0.1"
schema_version = 1
authors = ["mantou132 <709922234@qq.com>"]
repository = "https://github.com/mantou132/gem"
snippets = "./snippets/typescript.json"

[language_servers.gem]
name = "Gem language server"
languages = ["TypeScript", "TSX", "JavaScript", "JSDoc"]
language_ids = { "TypeScript" = "typescript", "TSX" = "typescriptreact", "JavaScript" = "javascript" }

[context_servers.gem]
name = "Gem Context Server"
